version: "3.3"

services:
  app:
    container_name: bts-dev-c
    image: bts-dev-i
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"
